### ISSUE TITLE
AutoBuilderCLI.jar does nothing, producing no output

### ISSUE THREAD

**Issue by lboklin** [acedogblast/ProjectUraniumAutoBuilder#1]
On NixOS I downloaded the jar file and ran `java -jar ./AutoBuilderCLI.jar x11 ../../../games/Pokemon\ Uranium\ 1.2.4/ ./ /nix/store/rj2zd98wiqylaqxylqq1638ibg8r2kxg-ffmpeg-full-4.2.3/bin/ffmpeg` and it successfully executes with no apparent changes to my files.

**Comment by acedogblast** [comment]
Currently only "dev-setup" is the only option for the {Target Platform}. Make sure your 3 paths are surrounded by double quotes if there are spaces in your path.

**Comment by lboklin** [comment]
That made it run properly. I got an exception though:
```
java.nio.file.NoSuchFileException: /data/Downloads/git/Godot/Project-Uranium-Godot/../../../games/Pokemon Uranium 1.2.4/Graphics/Pictures/Map_icon - C�pia.png
```

**Comment by lboklin** [comment]
After running it and opening the Godot project, Godot complains about missing resource:
```
E 0:00:00.386   poll: res://Utilities/Menu.tscn:17 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Graphics/Windowskins/skin1.png
  <C++ Source>  scene/resources/resource_format_text.cpp:440 @ poll()
```

**Comment by lboklin** [comment]
I took the liberty of [rewriting it in Haskell](https://github.com/lboklin/ProjectUraniumAutoBuilderHs) (mostly because I was curious to see how it would translate and because the issue I've encountered(at least in part?) with this one appears to be with character encoding, which I don't know how to fix in Java).
